In [25]:
#numpy - numerical python

import numpy as np
import sys
import time

In [5]:
li = [i for i in range(1000000)]

In [6]:
sys.getsizeof(li)

8448728

In [7]:
arr = np.array(li)
sys.getsizeof(arr)

8000112

In [9]:
sys.getsizeof([1,2,3])
88-56

32

In [10]:
32/3

10.666666666666666

In [11]:
arr = np.array([1,2,3])
sys.getsizeof(arr)

136

In [12]:
136-112

24

In [13]:
24/3

8.0

In [15]:
arr = np.random.randint(2,25,7)
arr

array([16, 14,  6, 19, 20, 20, 11], dtype=int32)

In [16]:
np.arange(2,50,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [17]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
1.73469388 - 1.55102041

0.18367347

In [19]:
7.06122449 - 6.87755102

0.18367346999999956

In [20]:
arr = np.array([[1,2,3],[4,5,6]])

In [21]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [23]:
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
list1 = [i for i in range(1,10000000)]
list2 = [i for i in range(1,10000000)]
list3 = [i for i in range(1,10000000)]
start = time.time()
for i in range(len(list1)):
    list3[i] = list1[i] + list2[i]
    
end = time.time()
total = end - start
total

2.080956220626831

In [27]:
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()

arr3 = arr1 + arr2
    
end = time.time()
total = end - start
total

0.049607038497924805

In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9])


In [29]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr1 = np.array([89,45,12,4,6,7])


In [32]:
arr2 = np.concatenate((arr,arr1))

In [33]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 89, 45, 12,  4,  6,  7])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

In [35]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
import random
np.random.seed(15)
arr = np.random.randint(2,25,7)
print(arr)
max(arr)
min(arr)
sum(arr)

[10 23 14  7  2  9 13]


np.int32(78)